//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsach2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeTracking
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateTimeTracking { get; set; }
        public string UserName { get; set; }
        public string TrackingName { get; set; }
        public string XMLTracking { get; set; }
    }
}
