//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsach2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issues_of_books
    {
        public int issues_of_books_ID { get; set; }
        public Nullable<System.DateTime> date_of_issues { get; set; }
        public Nullable<System.DateTime> date_of_comeback { get; set; }
        public int book_ID { get; set; }
        public int student_ID { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Student Student { get; set; }
    }
}
