//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsach2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Issues_of_books = new HashSet<Issues_of_books>();
            this.Student_grade = new HashSet<Student_grade>();
        }
    
        public int passport_ID { get; set; }
        public int student_ID { get; set; }
        public int group_ID { get; set; }
        public Nullable<decimal> scholarship { get; set; }
        public int place_in_rating { get; set; }
        public Nullable<int> dorm_room { get; set; }
        public Nullable<bool> headmaster { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issues_of_books> Issues_of_books { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_grade> Student_grade { get; set; }
    }
}
